CREATE OR REPLACE FUNCTION public.is_portfolio_owner() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT EXISTS (SELECT 1 FROM auth.users WHERE id = auth.uid() AND lower(email) = 'tatikorostyleva2194@gmail.com' AND email_confirmed_at IS NOT NULL) $$;
GRANT EXECUTE ON FUNCTION public.is_portfolio_owner() TO anon, authenticated;
CREATE TABLE public.portfolio_cases (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), slug text NOT NULL UNIQUE, title text NOT NULL, summary text NOT NULL DEFAULT '', contribution text NOT NULL DEFAULT '', outcome text NOT NULL DEFAULT '', role text NOT NULL DEFAULT '', period text NOT NULL DEFAULT '', stage text NOT NULL DEFAULT '', cover_path text, sections jsonb NOT NULL DEFAULT '[]'::jsonb, links jsonb NOT NULL DEFAULT '[]'::jsonb, nda boolean NOT NULL DEFAULT false, published boolean NOT NULL DEFAULT false, featured boolean NOT NULL DEFAULT false, sort_order integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.portfolio_cases TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.portfolio_cases TO authenticated;
GRANT ALL ON public.portfolio_cases TO service_role;
ALTER TABLE public.portfolio_cases ENABLE ROW LEVEL SECURITY;
CREATE POLICY cases_public_read ON public.portfolio_cases FOR SELECT TO anon, authenticated USING (published OR public.is_portfolio_owner());
CREATE POLICY cases_owner_insert ON public.portfolio_cases FOR INSERT TO authenticated WITH CHECK (public.is_portfolio_owner());
CREATE POLICY cases_owner_update ON public.portfolio_cases FOR UPDATE TO authenticated USING (public.is_portfolio_owner()) WITH CHECK (public.is_portfolio_owner());
CREATE POLICY cases_owner_delete ON public.portfolio_cases FOR DELETE TO authenticated USING (public.is_portfolio_owner());
CREATE TABLE public.portfolio_settings (id integer PRIMARY KEY DEFAULT 1 CHECK (id = 1), about text NOT NULL DEFAULT '', email text NOT NULL DEFAULT '', telegram text NOT NULL DEFAULT '', resume_path text, updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.portfolio_settings TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.portfolio_settings TO authenticated;
GRANT ALL ON public.portfolio_settings TO service_role;
ALTER TABLE public.portfolio_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY settings_public_read ON public.portfolio_settings FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY settings_owner_insert ON public.portfolio_settings FOR INSERT TO authenticated WITH CHECK (public.is_portfolio_owner());
CREATE POLICY settings_owner_update ON public.portfolio_settings FOR UPDATE TO authenticated USING (public.is_portfolio_owner()) WITH CHECK (public.is_portfolio_owner());
CREATE POLICY settings_owner_delete ON public.portfolio_settings FOR DELETE TO authenticated USING (public.is_portfolio_owner());
CREATE TABLE public.portfolio_media (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), case_id uuid NOT NULL REFERENCES public.portfolio_cases(id) ON DELETE CASCADE, path text NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.portfolio_media TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.portfolio_media TO authenticated;
GRANT ALL ON public.portfolio_media TO service_role;
ALTER TABLE public.portfolio_media ENABLE ROW LEVEL SECURITY;
CREATE POLICY media_public_read ON public.portfolio_media FOR SELECT TO anon, authenticated USING (public.is_portfolio_owner() OR EXISTS (SELECT 1 FROM public.portfolio_cases c WHERE c.id = case_id AND c.published));
CREATE POLICY media_owner_insert ON public.portfolio_media FOR INSERT TO authenticated WITH CHECK (public.is_portfolio_owner());
CREATE POLICY media_owner_update ON public.portfolio_media FOR UPDATE TO authenticated USING (public.is_portfolio_owner()) WITH CHECK (public.is_portfolio_owner());
CREATE POLICY media_owner_delete ON public.portfolio_media FOR DELETE TO authenticated USING (public.is_portfolio_owner());
CREATE POLICY portfolio_storage_owner_read ON storage.objects FOR SELECT TO authenticated USING (bucket_id = 'portfolio-media' AND public.is_portfolio_owner());
CREATE POLICY portfolio_storage_owner_insert ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'portfolio-media' AND public.is_portfolio_owner() AND (storage.foldername(name))[1] = auth.uid()::text);
CREATE POLICY portfolio_storage_owner_update ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'portfolio-media' AND public.is_portfolio_owner()) WITH CHECK (bucket_id = 'portfolio-media' AND public.is_portfolio_owner());
CREATE POLICY portfolio_storage_owner_delete ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'portfolio-media' AND public.is_portfolio_owner());
CREATE POLICY portfolio_storage_public_read ON storage.objects FOR SELECT TO anon, authenticated USING (bucket_id = 'portfolio-media' AND (EXISTS (SELECT 1 FROM public.portfolio_media m JOIN public.portfolio_cases c ON c.id = m.case_id WHERE m.path = name AND c.published) OR EXISTS (SELECT 1 FROM public.portfolio_settings s WHERE s.resume_path = name)));
CREATE OR REPLACE FUNCTION public.touch_portfolio_updated_at() RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END $$;
CREATE TRIGGER touch_cases BEFORE UPDATE ON public.portfolio_cases FOR EACH ROW EXECUTE FUNCTION public.touch_portfolio_updated_at();
CREATE TRIGGER touch_settings BEFORE UPDATE ON public.portfolio_settings FOR EACH ROW EXECUTE FUNCTION public.touch_portfolio_updated_at();
CREATE TRIGGER touch_media BEFORE UPDATE ON public.portfolio_media FOR EACH ROW EXECUTE FUNCTION public.touch_portfolio_updated_at();
INSERT INTO public.portfolio_settings (id, about, email, telegram) VALUES (1, 'I start by understanding the problem, the business behind it, and the constraints that shape it. I map the full customer experience — including the operational work that happens out of sight — and work closely with product, engineering, analytics, and compliance to test decisions before delivery. Design systems help me keep complex products coherent; prototyping beyond Figma, including low-code and AI-assisted tools, helps make ideas tangible early.', 'tatikorostyleva2194@gmail.com', 'https://t.me/tiana_koro');
INSERT INTO public.portfolio_cases (slug,title,summary,contribution,outcome,role,period,stage,sections,nda,published,featured,sort_order) VALUES
('kyc-kyb-onboarding','KYC/KYB onboarding for individuals and businesses','Making registration and verification workable across individuals, companies, documents, review states, and compliance constraints.','Research, benchmarking, branching journeys, verification states, and an early-access model.','Designed an onboarding model that lets partners explore the portal before verification. Smaller partners represented 10–20% of program profit; that figure is segment context, not a redesign outcome.','Area Product Designer / Project Lead','2025–2026','Designed; full rollout not claimed','[{"title":"Context and constraints","text":"The previous entry model delayed access until verification was complete and excluded partners with fewer than five clients. Compliance requirements still had to govern document collection, review, and approval."},{"title":"Research and insights","text":"I benchmarked comparable products and examined the value of smaller partners. This informed a model that separates early exploration of the portal from access to regulated actions."},{"title":"Key decisions","text":"Entry → identify individual or business → collect the relevant documents → review and approval. In parallel, allow limited early access while verification is pending. Exception paths account for missing documents, additional review, and different risk profiles. The exact permissions at each stage depend on compliance approval."},{"title":"Flows and interface","text":"The important design work was the branching logic: which information is required, when a partner can enter the portal, what each review state communicates, and how an exception returns to the main path. A full flow and readable decision-level excerpts can be added here."},{"title":"Outcomes and learnings","text":"The resulting model widened the proposed entry path while retaining verification controls. A full launch or conversion lift is not claimed."}]',true,true,true,1),
('b2b-rebates-payouts','Redesigning B2B rebates and payouts','Restructuring partner-to-client payouts as regulatory requirements changed.','An interim solution, future payout mechanics, states and exceptions, a Cursor prototype, and partner testing.','An interim solution was implemented. The automated flow was refined with partners and prepared for development and a pilot; prevention of $XXXk in losses was an estimate.','Area Product Designer','2025–2026','Interim solution implemented; target flow prepared for pilot','[{"title":"Context and constraints","text":"A licensing transition affected the existing form of partner-to-client rebates. The work needed to retain the program while meeting new regulatory requirements."},{"title":"Research and insights","text":"I investigated constraints with legal and product partners and tested an interactive Cursor prototype with partners. Feedback informed adjustments before development."},{"title":"Key decisions","text":"First, an interim rebate option maintained continuity under the constraints. Separately, I designed an automated flow covering calculation, payout rules, statuses, manual actions, and exceptions."},{"title":"Flows and interface","text":"The target design brings payout review, setup, status, and exception handling into a coherent workflow. It was prepared for development and a test launch, not presented as fully deployed."},{"title":"Outcomes and learnings","text":"The temporary solution was implemented. The target flow was handed off for development and pilot testing. Estimated loss prevention is not confirmed revenue growth."}]',true,true,true,2),
('standalone-partner-portal','Designing a standalone B2B partner portal','Turning a partner area into an independent product through organizational and licensing changes.','Workflow audit, customer journeys, service blueprints, product structure, interface design, and transition planning.','The transition preserved partner access while operational processes were reorganized; this does not imply every designed section launched.','Area Product Designer','2025–2026','Transition completed; sections at different delivery stages','[{"title":"Context and constraints","text":"The partner program moved away from shared company infrastructure during organizational and licensing changes. Partner access and support processes had to remain coherent throughout the transition."},{"title":"Research and insights","text":"I audited the existing partner journey and its operational dependencies, using customer journeys and service blueprints to expose work behind the interface."},{"title":"Key decisions","text":"I mapped what partners needed at each stage, defined the product structure and transition dependencies, and coordinated interface and service changes with cross-functional teams."},{"title":"Flows and interface","text":"The portal work spans dashboard, partner operations, and transition touchpoints. The design distinguished between the new product vision and the specific capabilities needed for a safe transition."},{"title":"Outcomes and learnings","text":"Partner access was preserved during the transition, with operational processes adapted. This is not a claim that all designed sections were launched."}]',true,true,true,3),
('new-b2b-business-model','Validating a new B2B business model','Testing revised partner program terms and explaining a more complex model.','Partner research, feedback analysis, presentation of terms, and portal adaptation.','80% of participating top partners accepted the proposed terms; pilot metrics remained stable.','Area Product Designer / Research Lead','2025–2026','Pilot','[{"title":"Context and constraints","text":"The partner program needed a new model that could be clearly explained and evaluated with its largest partners."},{"title":"Research and insights","text":"I worked through partner feedback to understand objections and improve how the new mechanics were communicated."},{"title":"Key decisions","text":"Present the terms clearly, adapt the interface where the model changes the experience, and test the proposal with participating top partners before wider decisions."},{"title":"Outcomes and learnings","text":"80% of participating top partners accepted the proposed terms; pilot metrics remained stable. This finding applies to the participants, not the whole partner base."}]',true,true,false,4),
('research-recruitment','Improving research recruitment','Finding more reliable ways to recruit B2B research participants.','Research planning with a researcher, interview guides, analysis, hypothesis checks, targeted invitations, and in-product surveys.','Reduced recruitment time by approximately 60% while doubling participant numbers.','Process Lead / Area Product Designer','2025–2026','Implemented research practice','[{"title":"Context and constraints","text":"Recruitment for B2B partner research was a bottleneck; the existing approach required several sprints to reach enough participants."},{"title":"Research and insights","text":"Together with a researcher I planned studies, wrote interview guides, analysed findings, and checked hypotheses while trying different recruitment methods."},{"title":"Key decisions","text":"Targeted invitations through partner managers and in-product surveys gave relevant participants clearer ways to join research."},{"title":"Outcomes and learnings","text":"Reduced recruitment time by approximately 60% while doubling participant numbers."}]',true,true,false,5),
('multi-user-accounts','Multi-user accounts and sub-accounts','A researched account structure for teams managing brands or regions.','Research and design of owner, employee permission, and nested sub-account models.','Researched and designed; not released to production.','Senior Product Designer','2025–2026','Research and design only','[{"title":"Context and constraints","text":"Teams needed a structure with a primary owner, employee permissions, and sub-accounts for brands or regions."},{"title":"Key decisions","text":"Research and design explored how account ownership and permission boundaries should work across nested entities."},{"title":"Outcomes and learnings","text":"Researched and designed; not released to production."}]',true,false,false,6);